apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prom-node-app
  name: prom-node-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: prom-node-app
  type: ClusterIP
status:
  loadBalancer: {}
